config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

    resources :combinations
    resources :boards
    resources :sensors
    resources :sensor_families
    resources :technologies
    resources :manufacturers

  
    root 'home#index'

  end

  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }, via: :get
  match '', to: redirect("/#{I18n.default_locale}"), via: :get

end

app/models/sensor_family.rb
class SensorFamily < ActiveRecord::Base

  has_many :sensors
  belongs_to :technology

  translates :name, :descr

end

app/controllers/sensor_families_controller.rb
class SensorFamiliesController < ApplicationController
  before_action :set_sensor_family, only: [:show, :edit, :update, :destroy]

  # GET /sensor_families
  # GET /sensor_families.json
  def index
    @sensor_families = SensorFamily.all
  end

  # GET /sensor_families/1
  # GET /sensor_families/1.json
  def show
  end

  # GET /sensor_families/new
  def new
    @sensor_family = SensorFamily.new
  end

  # GET /sensor_families/1/edit
  def edit
  end

  # POST /sensor_families
  # POST /sensor_families.json
  def create
    @sensor_family = SensorFamily.new(sensor_family_params)

    respond_to do |format|
      if @sensor_family.save
        format.html { redirect_to @sensor_family, notice: 'Sensor family was successfully created.' }
        format.json { render :show, status: :created, location: @sensor_family }
      else
        format.html { render :new }
        format.json { render json: @sensor_family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensor_families/1
  # PATCH/PUT /sensor_families/1.json
  def update
    respond_to do |format|
      if @sensor_family.update(sensor_family_params)
        format.html { redirect_to @sensor_family, notice: 'Sensor family was successfully updated.' }
        format.json { render :show, status: :ok, location: @sensor_family }
      else
        format.html { render :edit }
        format.json { render json: @sensor_family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensor_families/1
  # DELETE /sensor_families/1.json
  def destroy
    @sensor_family.destroy
    respond_to do |format|
      format.html { redirect_to sensor_families_url, notice: 'Sensor family was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor_family
      @sensor_family = SensorFamily.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_family_params
      params.require(:sensor_family).permit(:name, :descr, :technology_id)
    end
end

app/helpers/sensor_families_helper.rb
module SensorFamiliesHelper
end

app/views/sensor_families/_form.html.erb
<%= simple_form_for(@sensor_family) do |f| %>
  <% if @sensor_family.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sensor_family.errors.count, "error") %> prohibited this sensor_family from being saved:</h2>

      <ul>
      <% @sensor_family.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <%= f.input :descr %>
  <%= f.association :technology, :include_blank => false %>
  <%= f.button :submit %>

<% end %>

app/views/sensor_families/edit.html.erb
<h1>Editing Sensor Family</h1>

<%= render 'form' %>

<%= link_to 'Show', @sensor_family %> |
<%= link_to 'Back', sensor_families_path %>

app/views/sensor_families/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sensor Families</h1>
<div class="table-responsive">
<table class="table table-hover custom">
  <thead>
    <tr>
      <th>Name</th>
      <th>Descr</th>
      <th>Technology</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sensor_families.each do |sensor_family| %>
      <tr  data-link="<%= sensor_family_path(sensor_family) %>">
        <td><%= sensor_family.name %></td>
        <td><%= sensor_family.descr %></td>
        <td><%= sensor_family.technology.name %></td>
        <td><%= link_to 'Show', sensor_family %></td>
        <td><%= link_to 'Edit', edit_sensor_family_path(sensor_family) %></td>
        <td><%= link_to 'Destroy', sensor_family, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Sensor family', new_sensor_family_path %>

app/views/sensor_families/new.html.erb
<h1>New Sensor Family</h1>

<%= render 'form' %>

<%= link_to 'Back', sensor_families_path %>

app/views/sensor_families/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sensor_family.name %>
</p>

<p>
  <strong>Descr:</strong>
  <%= @sensor_family.descr %>
</p>

<p>
  <strong>Technology:</strong>
  <%= @sensor_family.technology %>
</p>

<%= link_to 'Edit', edit_sensor_family_path(@sensor_family) %> |
<%= link_to 'Back', sensor_families_path %>