config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

    resources :combinations
    resources :boards
    resources :sensors
    resources :sensor_families
    resources :technologies
    resources :manufacturers

  
    root 'home#index'

  end

  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }, via: :get
  match '', to: redirect("/#{I18n.default_locale}"), via: :get

end

app/models/sensor.rb
class Sensor < ActiveRecord::Base

  has_many :combinations
  belongs_to :manufacturer
  belongs_to :sensor_family

  translates :name, :descr

end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :set_sensor, only: [:show, :edit, :update, :destroy]

  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.all
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor was successfully created.' }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1
  # PATCH/PUT /sensors/1.json
  def update
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sensor }
      else
        format.html { render :edit }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to sensors_url, notice: 'Sensor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_params
      params.require(:sensor).permit(:pn, :name, :descr, :size, :manufacturer_id, :sensor_family_id)
    end
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/sensors/_form.html.erb
<%= simple_form_for(@sensor) do |f| %>
  <% if @sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
      <% @sensor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  
  <%= f.input :pn %>
  <%= f.input :name %>
  <%= f.input :descr %>
  <%= f.input :size %>
  <%= f.association :manufacturer, :include_blank => false %>
  <%= f.association :sensor_family, :include_blank => false %>
  <%= f.button :submit %>

<% end %>

app/views/sensors/edit.html.erb
<h1>Editing Sensor</h1>

<%= render 'form' %>

<%= link_to 'Show', @sensor %> |
<%= link_to 'Back', sensors_path %>

app/views/sensors/index.html.erb
<header id="list-sensors">
  <div class="container">

<p id="notice"><%= notice %></p>

<h1>Listing Sensors</h1>

<table class="table table-hover custom">
  <thead>
    <tr>
      <th>Pn</th>
      <th>Name</th>
      <th>Descr</th>
      <th>Sensor family</th>
      <th>Tipo sensore</th>
      <th>Size</th>
      <th>Manufacturer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sensors.each do |sensor| %>
      <tr   data-link="<%= sensor_path(sensor) %>">
        <td><%= sensor.pn %></td>
        <td><%= sensor.name %></td>
        <td><%= sensor.descr %></td>
        <td><%= sensor.sensor_family.name %></td>
        <td><%= sensor.sensor_family.technology.name%></td>
        <td><%= sensor.size %></td>
        <td><%= sensor.manufacturer.name %></td>
        <td><%= link_to 'Show', sensor %></td>
        <td><%= link_to 'Edit', edit_sensor_path(sensor) %></td>
        <td><%= link_to 'Destroy', sensor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sensor', new_sensor_path %>

  </div>
</header>

app/views/sensors/new.html.erb
<h1>New Sensor</h1>

<%= render 'form' %>

<%= link_to 'Back', sensors_path %>

app/views/sensors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pn:</strong>
  <%= @sensor.pn %>
</p>

<p>
  <strong>Name:</strong>
  <%= @sensor.name %>
</p>

<p>
  <strong>Descr:</strong>
  <%= @sensor.descr %>
</p>

<p>
  <strong>Size:</strong>
  <%= @sensor.size %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @sensor.manufacturer %>
</p>

<p>
  <strong>Sensor family:</strong>
  <%= @sensor.sensor_family %>
</p>

<%= link_to 'Edit', edit_sensor_path(@sensor) %> |
<%= link_to 'Back', sensors_path %>