config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

    resources :combinations
    resources :boards
    resources :sensors
    resources :sensor_families
    resources :technologies
    resources :manufacturers

  
    root 'home#index'

  end

  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }, via: :get
  match '', to: redirect("/#{I18n.default_locale}"), via: :get

end

app/models/technology.rb
class Technology < ActiveRecord::Base
  has_many :sensor_families
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
  before_action :set_technology, only: [:show, :edit, :update, :destroy]

  # GET /technologies
  # GET /technologies.json
  def index
    @technologies = Technology.all
  end

  # GET /technologies/1
  # GET /technologies/1.json
  def show
  end

  # GET /technologies/new
  def new
    @technology = Technology.new
  end

  # GET /technologies/1/edit
  def edit
  end

  # POST /technologies
  # POST /technologies.json
  def create
    @technology = Technology.new(technology_params)

    respond_to do |format|
      if @technology.save
        format.html { redirect_to @technology, notice: 'Technology was successfully created.' }
        format.json { render :show, status: :created, location: @technology }
      else
        format.html { render :new }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /technologies/1
  # PATCH/PUT /technologies/1.json
  def update
    respond_to do |format|
      if @technology.update(technology_params)
        format.html { redirect_to @technology, notice: 'Technology was successfully updated.' }
        format.json { render :show, status: :ok, location: @technology }
      else
        format.html { render :edit }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /technologies/1
  # DELETE /technologies/1.json
  def destroy
    @technology.destroy
    respond_to do |format|
      format.html { redirect_to technologies_url, notice: 'Technology was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technology
      @technology = Technology.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def technology_params
      params.require(:technology).permit(:name, :descr)
    end
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/views/technologies/_form.html.erb
<%= form_for(@technology) do |f| %>
  <% if @technology.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@technology.errors.count, "error") %> prohibited this technology from being saved:</h2>

      <ul>
      <% @technology.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :descr %><br>
    <%= f.text_field :descr %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/technologies/edit.html.erb
<h1>Editing Technology</h1>

<%= render 'form' %>

<%= link_to 'Show', @technology %> |
<%= link_to 'Back', technologies_path %>

app/views/technologies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Technologies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Descr</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @technologies.each do |technology| %>
      <tr>
        <td><%= technology.name %></td>
        <td><%= technology.descr %></td>
        <td><%= link_to 'Show', technology %></td>
        <td><%= link_to 'Edit', edit_technology_path(technology) %></td>
        <td><%= link_to 'Destroy', technology, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Technology', new_technology_path %>

app/views/technologies/new.html.erb
<h1>New Technology</h1>

<%= render 'form' %>

<%= link_to 'Back', technologies_path %>

app/views/technologies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @technology.name %>
</p>

<p>
  <strong>Descr:</strong>
  <%= @technology.descr %>
</p>

<%= link_to 'Edit', edit_technology_path(@technology) %> |
<%= link_to 'Back', technologies_path %>